name: Monthly issue metrics
on:
  push:
    branches:
      - master

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest

    steps:
    - name: Get dates for last month
      shell: bash
      run: |
        # Calculate the date of one month ago
        one_month_ago=$(date -d "1 month ago" +%Y-%m-%d)
        # Get today's date
        today=$(date +%Y-%m-%d)
        #Set an environment variable with the date range
        echo "one_month_period=$one_month_ago..$today" >> "$GITHUB_ENV"
    - name: Run issue-metrics tool
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:tanobe/practice_with_YumemiWeather is:"issue pr" created:${{ env.last_month }} -reason:"not planned"'

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Monthly issue metrics report
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md
        assignees: <YOUR_GITHUB_HANDLE_HERE>
