name: pull-request-analytics
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 1'

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest

    steps:
    - name: Get dates for last week
      shell: bash
      run: |
        # Calculate the first day of the previous week
        first_day=$(date -d "14 days ago" +%Y-%m-%d)

        # Calculate the last day of the previous week
        last_day=$(date -d "1 day ago" +%Y-%m-%d)

        # Set an environment variable with the date range
        echo "last_week=$first_day..$last_day" >> "$GITHUB_ENV"

    - name: Run issue-metrics tool
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:tanobe/practice_with_YumemiWeather is:"pr" created:${{ env.last_week }}'

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: issue metrics report
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md
        LABELS_TO_MEASURE: 'ready for review'
        HIDE_TIME_TO_ANSWER: false
        assignees: |
          tanobe
          tanobe2
