name: pull-request-analytics
on:
  workflow_dispatch:
  schedule:
    # UTCの1:30は日本時間の10:30、スケジュール自体は毎週月曜日に設定
    - cron: '30 1 * * 1'

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest

    steps:
    - name: Get dates for last week
      shell: bash
      run: |
        # Calculate the first day of the previous week
        first_day=$(date -d "14 days ago" +%Y-%m-%d)

        # Calculate the last day of the previous week
        last_day=$(date -d "1 day ago" +%Y-%m-%d)

        # Set an environment variable with the date range
        echo "last_week=$first_day..$last_day" >> "$GITHUB_ENV"

    # 週番号で、偶数なら成功して終了させる
    - name: Check if its time to run
      shell: bash
      run: |
        # Get the current week number
        week_number=$(date +%V)
        # If the week number is even, exit the job
        if (( week_number % 2 == 0 )); then
          exit 0
        fi

    - name: Run issue-metrics tool
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:tanobe/practice_with_YumemiWeather is:"pr" created:${{ env.last_week }}'

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: issue metrics report
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md
        LABELS_TO_MEASURE: 'ready for review'
        HIDE_TIME_TO_ANSWER: true
        assignees: |
          tanobe
          tanobe2
